### PR TITLE
Refactor consent code spec to support variable codes

### PR DESCRIPTION
**Pull request by mcupak**

### CODE REVIEW

**Review by sdelatorrep — COMMENTED** [review]
What about adding an extra field to accommodate this information? e.g. "extra_info". I dislike making the field text free (we are providing just a comment with the list of accepted values). WDYT?

**Comment by mcupak** [comment]
I like that. Do you know if there is a way to express inheritance in proto3 so that we could also correctly differentiate primary/secondary and basic/with extra info?

**Comment by sdelatorrep** [comment]
mmm, it does not seem so...
> Don't go looking for facilities similar to class inheritance, though – protocol buffers don't do that. 
([source](https://developers.google.com/protocol-buffers/docs/javatutorial))

I've been googling a little but I don't see/like any workaround...

**Comment by mcupak** [comment]
I'm merging this since it addresses a bug, but is ultimately superseded by the OpenAPI version.

**Pull request merged**
