### PR TITLE
Update Contributing.md to reflect OpenAPI conventions (issue #7)

### PR DESCRIPTION
**Pull request by sdelatorrep**
Update Contributing.md to reflect OpenAPI conventions (issue #7).

### CODE REVIEW

**Comment by sdelatorrep** [comment]
Travis fails because it can't find the files (they are in my local repo but I can't create branches here).

**Comment by sdelatorrep** [comment]
Hi @mcupak , could you have a look at this, please? Thanks!

**Comment by mcupak** [comment]
@sdelatorrep Will do. Issue: #18

**Comment by mcupak** [comment]
@sdelatorrep I submitted #19 to fix the build issue. Please review and if OK rebase this PR onto it.

**Comment by sdelatorrep** [comment]
Hi @mcupak , I did the rebase but do you know why Travis is failing with this error?
`The job exceeded the maximum log length, and has been terminated.`
I saw you also got this error some days ago with the last PR you did but I don't know if you solved it somehow or just ignored it. Many thanks!

**Comment by sdelatorrep** [comment]
Hi @mcupak , please, see my comments [here](https://github.com/ga4gh-beacon/specification/pull/266) as some things have changed in the Swagger Validator repo.

**Comment by mcupak** [comment]
I'll wait for the review of https://github.com/ga4gh-beacon/specification/pull/268, and we can then incorporate a similar solution here.

**Comment by mcupak** [comment]
@sdelatorrep #20

**Comment by sdelatorrep** [comment]
Hi @mcupak, could you merge this PR and do a release if there is nothing else missing? I don't have write access so I can't do any of these actions. Thanks!

**Pull request merged**
